# Generated by Django 3.1.2 on 2020-11-17 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20201117_1625'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcategory',
            old_name='name',
            new_name='category',
        ),
    ]
