# Generated by Django 3.1.2 on 2020-11-26 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20201117_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='category',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Категория'),
        ),
    ]
