# Generated by Django 3.1.2 on 2020-11-11 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_auto_20201111_1744'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'verbose_name': 'Подписчик', 'verbose_name_plural': 'Подписчики'},
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='sub_email',
            field=models.EmailField(max_length=254, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='sub_name',
            field=models.CharField(max_length=200, verbose_name='Имя подписчика'),
        ),
    ]
