# Generated by Django 3.1.2 on 2020-11-13 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_auto_20201111_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='sub_name',
            field=models.CharField(max_length=200, verbose_name='Имя'),
        ),
    ]
